- name: Load environment_monitor_ansible executables.
  import_role:
    name: get_ansible_binaries
  vars:
    get_ansible_binaries_application: environment_monitor_ansible
    get_ansible_binaries_version: '{{ environment_monitor_ansible_version }}'

- name: Copy, and start environment monitor
  block:
    - name: Copy over service file.
      become: true
      template:
        src: templates/environment_monitor_ansible.service
        dest: /etc/systemd/system/environment_monitor_ansible.service
        owner: root
        group: root
        mode: '0644'

    - name: Copy over executable.
      become: true
      copy:
        src:
          "{{ get_ansible_binaries_directory.path }}/build/{{
          ansible_facts['system'] }}/{{ ansible_facts['architecture']
          }}/environment_monitor_ansible"
        dest: /usr/local/bin/environment_monitor_ansible
        owner: root
        group: root
        mode: '0755'

    - name: Start systemd servce.
      become: true
      systemd:
        enabled: true
        state: restarted
        name: environment_monitor_ansible
        daemon_reload: true
  when: install_environment_monitor__needs_environment_monitor is defined and install_environment_monitor__needs_environment_monitor == true
