# Libraries needed for x86_64 Skia builds and tests.
#
# As an example, Test-Debian10-Clang-GCE-CPU-AVX2-x86_64-Debug-All-SafeStack needs these packages,
# or it will fail because "dm" is missing necessary shared libraries.
#
# Based on
# https://skia.googlesource.com/buildbot/+/911443de263af2792cfc8bfaf8d793826e2ca9e2/go/gce/swarming/setup-script-linux.sh#16
- name: Install x86_64 libraries
  become: true
  apt:
    pkg:
      - libc++-dev
      - libxi-dev

# Libraries needed for x86 (32-bit) Skia builds and tess.
#
# As an example, Test-Debian10-Clang-GCE-CPU-AVX2-x86-Debug-All needs these packages, or it will
# fail because "dm" is missing necessary shared libraries.
#
# Based on
# https://skia.googlesource.com/buildbot/+/911443de263af2792cfc8bfaf8d793826e2ca9e2/go/gce/swarming/setup-script-linux.sh#32.
- name: Support for x86 (i.e. 32-bit builds).
  block:
    - name: Add i386 architecture
      become: true
      shell: dpkg --add-architecture i386

    - name: Install x86 (i.e. 32-bit) libraries
      become: true
      apt:
        update_cache: true # Run "apt-get update" before the operation.
        pkg:
          - libfreetype6:i386
          - libfontconfig1:i386
          - libgl1-mesa-glx:i386
          - libglu1-mesa:i386
          - libx11-6:i386
          - libxext-dev:i386
          - g++-multilib

    - name: Link libfreetype.so.6 -> libfreetype.so
      become: true
      file:
        src: /usr/lib/i386-linux-gnu/libfreetype.so.6
        dest: /usr/lib/i386-linux-gnu/libfreetype.so
        state: link

    - name: Link libfontconfig.so.6 -> libfontconfig.so
      become: true
      file:
        src: /usr/lib/i386-linux-gnu/libfontconfig.so.1
        dest: /usr/lib/i386-linux-gnu/libfontconfig.so
        state: link

    - name: Link libGLU.so.1 -> libGLU.so
      become: true
      file:
        src: /usr/lib/i386-linux-gnu/libGLU.so.1
        dest: /usr/lib/i386-linux-gnu/libGLU.so
        state: link

    - name: Link libGL.so.1 -> libGL.so
      become: true
      file:
        src: /usr/lib/i386-linux-gnu/libGL.so.1
        dest: /usr/lib/i386-linux-gnu/libGL.so
        state: link

    - name: Link libfreetype.so.6 -> libX11.so
      become: true
      file:
        src: /usr/lib/i386-linux-gnu/libX11.so.6.3.0
        dest: /usr/lib/i386-linux-gnu/libX11.so
        state: link

- name: Install packages needed by the Skia Bazel build.
  become: true
  apt:
    update_cache: true # Run "apt-get update" before the operation. lovisolo@ found this necessary.
    pkg:
      # Bazel needs "zip" to pack undeclared test outputs into an outputs.zip file under
      # the "bazel-testlogs" directory inside the Skia repository checkout.
      - zip
      # Without "git", Bazel fails to fetch some external repositories. This causes errors such as:
      #
      #     error running 'git init /home/chrome-bot/bazel_cache/fad...37d/external/libpng' while
      #     working with @libpng: ... "execvp(git, ...)": No such file or directory
      - git
